### ISSUE TITLE
Disabling health checks has no affect

### ISSUE THREAD

**Issue by magick93** [astefanutti/spring-boot-camel-rest-sql#1]
In the `application.yml` there is the following, which I have changed to settings:

```
endpoints:
  enabled: true
  health:
    enabled: false
```

However when I deploy to my openshift cluster I can see that the deployment config still has health checks. So it seems this setting doesnt do anything.
